language: php
sudo: false

services:
  - docker

php:
- '5.6'
- '7.0'
- '7.1'
- hhvm

env:
- GITVERSION="gittools/gitversion:5.0.0-linux-debian-9-netcoreapp2.2"

matrix:
  fast_finish: true
  allow_failures:
  - php: hhvm

before_install:
 - git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags

install:
- wget https://raw.githubusercontent.com/magento/marketplace-tools/master/validate_m2_package.php
- docker pull $GITVERSION

before_script:
- 
- docker run --rm -v "$(pwd):/repo" $GITVERSION /repo /output BuildServer
- export ARCHIVE=${TRAVIS_REPO_SLUG#PayEx/}-${GitVersion_FullSemVer}.zip
- echo $ARCHIVE
- zip -r $ARCHIVE *

script:
- php validate_m2_package.php -d $ARCHIVE

deploy:
  provider: releases
  api_key:
    secure: T31P9eRFFU1fH1dGyqd2gOvvW6Ln3+eepe1hPjGaig+YLkiQxY20DYowyiiMkl12HnMFdqby3EjZ4QjJ3N62Ym9m19tdnuniVLEUFF+lHhrThPRX6wtecNFkgSWLD6V4gptkBuoXWcKW67qzcISFgHt/RA799Ic9BFNXCjyZcuziFSRVHtrs2MUaf8mRzseynZgrRFnzMJjXqeiFbg6Dexh4Fqb9p15UouGbFk7c8dnwo7ruc68jmCnZ71Dz+YxDiMYpCbCwZJx5eTl4RlO39Bj9hlVh+UlMiHazRK3uQquWEzbqxhlPA6JLF2hHmiiMrOiVdMZ9bQ4f9PDO7HcWi0Op6kleaBJ6yX7GPItSPn3jXpeqs4AKjlRtxP1pCVHZ/w9GPYjbJ/Hp2wx2logHjrqSmoh0ZAJlS0RBPb/ojQa/uu1J2hj4ycQP3BnxtTiJyPvfiG6l6fx4t0jE26ubQ2yiBbg9lSxogqBkF12M5n579gXHUUaeX5t6uYFnivC5ay1P0v37YiT/E9G/gT/k4GLG4o655Tggq6k9nHiB2lrchzH2dIc2x4IvIKK7TJ7z1bXIu2ICW1aUWnWoP7t1Pp8zsGNYeaHc5OftPIYEnpfETYSg5U1J1ioDxXb28OxMmAPRTIlH2KOi+0s2KpNnB03zqAe/W7Ag+kzi5Vwlxng=
  file: "$ARCHIVE"
  skip_cleanup: true
  on:
    tags: true